### ISSUE TITLE
Комментариев на русском быть не должно, выносите см тогда в название переменных

### ISSUE THREAD

**Issue by coursar** [AleksandrNagovitsyn/02.Wallpaper#2]
https://github.com/AleksandrNagovitsyn/02.Wallpaper/blob/6ea564ddae97269c1a5792ee2f595e43f8157dff/src/Main.java#L3

**Comment by AleksandrNagovitsyn** [comment]
@coursar сделно

**Comment by coursar** [comment]
Зачем вы сделали Reopen?

**Comment by AleksandrNagovitsyn** [comment]
@coursar Вы тут #1  написали так сделать
