### ISSUE TITLE
Нужно количество целых рулонов

### ISSUE THREAD

**Issue by coursar** [AleksandrNagovitsyn/02.Wallpaper#3]
https://github.com/AleksandrNagovitsyn/02.Wallpaper/blob/6ea564ddae97269c1a5792ee2f595e43f8157dff/src/Main.java#L12-L13

**Comment by AleksandrNagovitsyn** [comment]
Иного выхода я не нашел. Если в int'ах делать, то число выходит явно меньше нужного. 

А как избавиться от дробной части в переменной rollNumber я так и не смог понять.

**Comment by coursar** [comment]
```java
int result = (int) doubleExpression;
```

**Comment by AleksandrNagovitsyn** [comment]
@coursar Сделано. Только не понял, почему надо ставить два оператора (int) и возводить expression в скобки

**Comment by coursar** [comment]
Надо было:
```java
   int rollNumber = (int)(clothNumber / clothNumberIntoRoll) + 1);
```
